/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service.ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import service.helper.ConnectionHelper;
import service.model.Customer;
import service.model.CustomerManager;
import service.model.Service;
import service.model.ServiceManager;
import service.model.UserManager;

/**
 *
 * @author CodeVector
 */
public class form_pengambilanservice extends javax.swing.JFrame {

    Service serviceGlobal;
    public static int id_user = 1;
    public form_menu a = null;

    /**
     * Creates new form form_login
     */
    public form_pengambilanservice() {
        initComponents();

    }

    public form_pengambilanservice(int id_service) {
        initComponents();
//        System.out.println();
        try {

            setServiceToComponent(id_service);
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    public void setServiceToComponent(int id_service) {
        try {
            Service service = ServiceManager.showService(id_service);
            service.setId_service(id_service);
            no_service.setText(String.valueOf(id_service));
            nama_barang.setText(service.getNama_barang());
            kerusakan.setText(service.getKerusakan());
            jenis_barang.setText(service.getJenis_barang());
            tanggal_selesai.setText(service.getTgl_selesai());
            System.out.println(service.getCustomer_nama());
            nama_customer.setText(service.getCustomer_nama());
            alamat_customer.setText(service.getCustomer_alamat());
            telp_customer.setText(service.getCustomer_no_hp());
            harga_service.setText(String.valueOf(service.getHarga_service()));

        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }
    }

//    public void setServiceToCustomer(int id_service){
//        try {
//            Service service = ServiceManager.showService(id_service);
//            no_service.setText(service.getId_service());
//            no_service.
//        } catch (Exception e) {
//        }
//    }
    public Boolean validateDataService() {
        boolean isCompleted = false;
        Service service = new Service();

        service.setId_service(Integer.parseInt(no_service.getText()));
        if (total_bayar.getText().isEmpty()) {
            service.setTotal_bayar(0);
        } else {
            service.setTotal_bayar(Integer.parseInt(total_bayar.getText()));
        }

        Date date = new Date();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar c = Calendar.getInstance();
        c.setTime(date);

        service.setTotal_kembalian(Integer.parseInt(kembalian.getText()));
        service.setTgl_ambil(sdf.format(c.getTime()));
        serviceGlobal = service;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_cariService = new javax.swing.JButton();
        no_service = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        kerusakan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama_customer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alamat_customer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telp_customer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        harga_service = new javax.swing.JTextField();
        btn_ambilService = new javax.swing.JButton();
        total_bayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        id_customer = new javax.swing.JTextField();
        tanggal_selesai = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tanggal_service = new javax.swing.JTextField();
        check_cetak = new javax.swing.JCheckBox();
        jenis_barang = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 52, 71));
        jLabel4.setText("Ambil Service");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btn_cariService.setBackground(new java.awt.Color(102, 102, 102));
        btn_cariService.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cariService.setForeground(new java.awt.Color(39, 52, 71));
        btn_cariService.setText("...");
        btn_cariService.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_cariService.setContentAreaFilled(false);
        btn_cariService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cariService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariServiceActionPerformed(evt);
            }
        });

        no_service.setEditable(false);
        no_service.setBackground(new java.awt.Color(248, 248, 248));
        no_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        no_service.setForeground(new java.awt.Color(137, 144, 155));
        no_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 52, 71));
        jLabel2.setText("No Service");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 52, 71));
        jLabel3.setText("Nama Barang");

        nama_barang.setBackground(new java.awt.Color(248, 248, 248));
        nama_barang.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        nama_barang.setForeground(new java.awt.Color(137, 144, 155));
        nama_barang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        kerusakan.setBackground(new java.awt.Color(248, 248, 248));
        kerusakan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        kerusakan.setForeground(new java.awt.Color(137, 144, 155));
        kerusakan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 52, 71));
        jLabel6.setText("Kerusakan");

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 52, 71));
        jLabel7.setText("Tanggal Selesai");

        nama_customer.setEditable(false);
        nama_customer.setBackground(new java.awt.Color(248, 248, 248));
        nama_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        nama_customer.setForeground(new java.awt.Color(137, 144, 155));
        nama_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        nama_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_customerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 52, 71));
        jLabel8.setText("Nama Pelanggan");

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(39, 52, 71));
        jLabel9.setText("Alamat Pelanggan");

        alamat_customer.setEditable(false);
        alamat_customer.setBackground(new java.awt.Color(248, 248, 248));
        alamat_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        alamat_customer.setForeground(new java.awt.Color(137, 144, 155));
        alamat_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        alamat_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat_customerActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(39, 52, 71));
        jLabel10.setText("No HP");

        telp_customer.setEditable(false);
        telp_customer.setBackground(new java.awt.Color(248, 248, 248));
        telp_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        telp_customer.setForeground(new java.awt.Color(137, 144, 155));
        telp_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        telp_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telp_customerActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(39, 52, 71));
        jLabel11.setText("Harga Service");

        harga_service.setEditable(false);
        harga_service.setBackground(new java.awt.Color(248, 248, 248));
        harga_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        harga_service.setForeground(new java.awt.Color(137, 144, 155));
        harga_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        harga_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_serviceActionPerformed(evt);
            }
        });
        harga_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_serviceKeyReleased(evt);
            }
        });

        btn_ambilService.setBackground(new java.awt.Color(39, 52, 71));
        btn_ambilService.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_ambilService.setForeground(new java.awt.Color(248, 248, 248));
        btn_ambilService.setText("Ambil Service");
        btn_ambilService.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_ambilService.setContentAreaFilled(false);
        btn_ambilService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ambilService.setOpaque(true);
        btn_ambilService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ambilServiceActionPerformed(evt);
            }
        });

        total_bayar.setBackground(new java.awt.Color(248, 248, 248));
        total_bayar.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        total_bayar.setForeground(new java.awt.Color(137, 144, 155));
        total_bayar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        total_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bayarActionPerformed(evt);
            }
        });
        total_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                total_bayarKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(39, 52, 71));
        jLabel12.setText("Total Bayar");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(39, 52, 71));
        jLabel13.setText("Kembalian");

        kembalian.setBackground(new java.awt.Color(248, 248, 248));
        kembalian.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        kembalian.setForeground(new java.awt.Color(137, 144, 155));
        kembalian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        id_customer.setBackground(new java.awt.Color(51, 51, 51));
        id_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        id_customer.setBorder(null);
        id_customer.setEnabled(false);
        id_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_customerActionPerformed(evt);
            }
        });

        tanggal_selesai.setBackground(new java.awt.Color(248, 248, 248));
        tanggal_selesai.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tanggal_selesai.setForeground(new java.awt.Color(137, 144, 155));
        tanggal_selesai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        tanggal_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_selesaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(39, 52, 71));
        jLabel14.setText("Jenis Barang");

        tanggal_service.setBackground(new java.awt.Color(51, 51, 51));
        tanggal_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tanggal_service.setBorder(null);
        tanggal_service.setEnabled(false);
        tanggal_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_serviceActionPerformed(evt);
            }
        });

        check_cetak.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        check_cetak.setText("Cetak");

        jenis_barang.setBackground(new java.awt.Color(248, 248, 248));
        jenis_barang.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jenis_barang.setForeground(new java.awt.Color(137, 144, 155));
        jenis_barang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(harga_service, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(kembalian)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cariService, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jenis_barang, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kerusakan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggal_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alamat_customer)
                                .addComponent(telp_customer)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(check_cetak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ambilService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_bayar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tanggal_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_cariService, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenis_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telp_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ambilService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(check_cetak))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tanggal_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_serviceActionPerformed

    private void tanggal_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_selesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_selesaiActionPerformed

    private void id_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_customerActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void total_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_bayarKeyReleased
        // TODO add your handling code here:
        if (this.total_bayar.getText().isEmpty()) {
            this.total_bayar.setText("0");
        }

        int total_service = Integer.parseInt(harga_service.getText());
        int total_bayar = Integer.parseInt(this.total_bayar.getText());
        int total = (total_bayar - total_service);
        kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_total_bayarKeyReleased

    private void total_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bayarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_total_bayarActionPerformed

    private void btn_ambilServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilServiceActionPerformed
        // TODO add your handling code here:
        int yes_option;
        if (validateDataService()) {
            if (check_cetak.isSelected()) {
                yes_option = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ?");
                if (yes_option == JOptionPane.YES_OPTION) {
                    ServiceManager.updateAmbilService(serviceGlobal, 
                            Integer.parseInt(no_service.getText()));
                    a.initTableService("");
                    try {
                        HashMap parameter = new HashMap();
                        Service service = ServiceManager.showService(
                                Integer.parseInt(no_service.getText()));
                        parameter.put("no_service", ServiceManager.getLastIdService());
                        parameter.put("tanggal_service", service.getTgl_service());
                        parameter.put("nama_pelanggan", nama_customer.getText());
                        parameter.put("telpon", telp_customer.getText());
                        parameter.put("nama_barang", nama_barang.getText());
                        parameter.put("jenis_barang", jenis_barang.getText());
                        parameter.put("tanggal_ambil", service.getTgl_ambil());
                        parameter.put("sparepart", service.getSparepart());
                        parameter.put("harga_sparepart", kerusakan.getText());
                        parameter.put("harga_service", service.getHarga_service());
                        parameter.put("total_service", harga_service.getText());
                        parameter.put("total_bayar", total_bayar.getText());
                        parameter.put("kembalian", kembalian.getText());
                        JasperPrint jp = JasperFillManager.fillReport(getClass().
                                getResourceAsStream(""
                                + "/service/report/ReportAmbilService.jasper"), 
                                parameter, ConnectionHelper.getConnection());

                        JasperViewer.viewReport(jp, false);
                    } catch (Exception e) {
                        Logger.getLogger(form_pengambilanservice.class.getName())
                                .log(Level.SEVERE, null, e);

                    }
                }
                this.dispose();
            } else {
                yes_option = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan ?");
                if (yes_option == JOptionPane.YES_OPTION) {
                    ServiceManager.updateAmbilService(serviceGlobal, 
                            Integer.parseInt(no_service.getText()));
                    a.initTableService("");
                }

                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_ambilServiceActionPerformed

    private void harga_serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_serviceKeyReleased
        // TODO add your handling code here:       
    }//GEN-LAST:event_harga_serviceKeyReleased

    private void harga_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_serviceActionPerformed

    private void telp_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telp_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telp_customerActionPerformed

    private void alamat_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat_customerActionPerformed

    private void nama_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_customerActionPerformed

    private void btn_cariServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariServiceActionPerformed
        // TODO add your handling code here:
        form_pilihservice a = new form_pilihservice();
        System.out.println(this.toString());
        a.pengambilanService = this;
        a.setVisible(true);
    }//GEN-LAST:event_btn_cariServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pengambilanservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_customer;
    private javax.swing.JButton btn_ambilService;
    private javax.swing.JButton btn_cariService;
    private javax.swing.JCheckBox check_cetak;
    private javax.swing.JTextField harga_service;
    private javax.swing.JTextField id_customer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jenis_barang;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kerusakan;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_customer;
    private javax.swing.JTextField no_service;
    private javax.swing.JTextField tanggal_selesai;
    private javax.swing.JTextField tanggal_service;
    private javax.swing.JTextField telp_customer;
    private javax.swing.JTextField total_bayar;
    // End of variables declaration//GEN-END:variables
}
