/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service.ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import service.helper.ConnectionHelper;
import service.model.Customer;
import service.model.CustomerManager;
import service.model.Service;
import service.model.ServiceManager;
import service.model.UserManager;

/**
 *
 * @author CodeVector
 */
public class form_editservice extends javax.swing.JFrame {

    Service serviceGlobal;
    public static int id_user = 1;

    public form_menu a = null;

    /**
     * Creates new form form_login
     */
    public form_editservice() {
        initComponents();

    }

    public form_editservice(int id_service) {
        initComponents();
//        System.out.println();
        try {

            setServiceToComponent(id_service);
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    public void setServiceToComponent(int id_service) {
        Service service = ServiceManager.showService(id_service);
        service.setId_service(id_service);

        no_service.setText(String.valueOf(service.getId_service()));
        nama_barang.setText(service.getNama_barang());
        kerusakan.setText(service.getKerusakan());
        harga_service.setText(String.valueOf(service.getHarga_service()));
        harga_sparepart.setText(String.valueOf(service.getHarga_sparepart()));
        total_service.setText(String.valueOf(service.getTotal_harga()));
    }

    public Boolean validateDataService() {
        boolean isCompleted = false;
        Service service = new Service();

        if (no_service.getText().isEmpty()) {
            isCompleted = false;
            no_service.requestFocus(true);
        } else {
            isCompleted = true;
            service.setId_service(Integer.parseInt(no_service.getText()));
        }
        service.setId_user(id_user);
        if (nama_barang.getText().isEmpty()) {
            isCompleted = false;
            nama_barang.requestFocus(true);
        } else {
            isCompleted = true;
            service.setNama_barang(nama_barang.getText());
        }
        if (kerusakan.getText().isEmpty()) {
            isCompleted = false;
            kerusakan.requestFocus(true);
        } else {
            isCompleted = true;
            service.setKerusakan(kerusakan.getText());
        }
        service.setJenis_barang(jenis_barang.getSelectedItem().toString());
        service.setTgl_service(tanggal_service.getText());
        if (harga_sparepart.getText().isEmpty()) {
            service.setHarga_sparepart(0);
        } else {
            service.setHarga_sparepart(Integer.parseInt(harga_sparepart.getText()));
        }

        if (harga_service.getText().isEmpty()) {
            isCompleted = false;
            harga_service.requestFocus(true);
        } else {
            isCompleted = true;
            service.setHarga_service(Integer.parseInt(harga_service.getText()));
        }
        if (total_service.getText().isEmpty()) {
            isCompleted = false;
            total_service.requestFocus(true);
        } else {
            isCompleted = true;
            service.setTotal_harga(Integer.parseInt(total_service.getText()));
        }

        serviceGlobal = service;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        no_service = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        kerusakan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        harga_service = new javax.swing.JTextField();
        btn_updateService = new javax.swing.JButton();
        harga_sparepart = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_service = new javax.swing.JTextField();
        id_customer = new javax.swing.JTextField();
        jenis_barang = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tanggal_service = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 52, 71));
        jLabel4.setText("Update Service");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        no_service.setEditable(false);
        no_service.setBackground(new java.awt.Color(248, 248, 248));
        no_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        no_service.setForeground(new java.awt.Color(137, 144, 155));
        no_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        no_service.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 52, 71));
        jLabel2.setText("No Service");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 52, 71));
        jLabel3.setText("Nama Barang");

        nama_barang.setBackground(new java.awt.Color(248, 248, 248));
        nama_barang.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        nama_barang.setForeground(new java.awt.Color(137, 144, 155));
        nama_barang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        kerusakan.setBackground(new java.awt.Color(248, 248, 248));
        kerusakan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        kerusakan.setForeground(new java.awt.Color(137, 144, 155));
        kerusakan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 52, 71));
        jLabel6.setText("Kerusakan");

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(39, 52, 71));
        jLabel11.setText("Harga Service");

        harga_service.setBackground(new java.awt.Color(248, 248, 248));
        harga_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        harga_service.setForeground(new java.awt.Color(137, 144, 155));
        harga_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        harga_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_serviceActionPerformed(evt);
            }
        });
        harga_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_serviceKeyReleased(evt);
            }
        });

        btn_updateService.setBackground(new java.awt.Color(39, 52, 71));
        btn_updateService.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_updateService.setForeground(new java.awt.Color(248, 248, 248));
        btn_updateService.setText("Update Service");
        btn_updateService.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_updateService.setContentAreaFilled(false);
        btn_updateService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_updateService.setOpaque(true);
        btn_updateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateServiceActionPerformed(evt);
            }
        });

        harga_sparepart.setBackground(new java.awt.Color(248, 248, 248));
        harga_sparepart.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        harga_sparepart.setForeground(new java.awt.Color(137, 144, 155));
        harga_sparepart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        harga_sparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_sparepartActionPerformed(evt);
            }
        });
        harga_sparepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_sparepartKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(39, 52, 71));
        jLabel12.setText("Harga Sparepart");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(39, 52, 71));
        jLabel13.setText("Total Harga Service");

        total_service.setBackground(new java.awt.Color(248, 248, 248));
        total_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        total_service.setForeground(new java.awt.Color(137, 144, 155));
        total_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        total_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_serviceActionPerformed(evt);
            }
        });

        id_customer.setBackground(new java.awt.Color(51, 51, 51));
        id_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        id_customer.setBorder(null);
        id_customer.setEnabled(false);
        id_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_customerActionPerformed(evt);
            }
        });

        jenis_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Komputer", "Laptop", "Printer" }));

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(39, 52, 71));
        jLabel14.setText("Jenis Barang");

        tanggal_service.setBackground(new java.awt.Color(51, 51, 51));
        tanggal_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tanggal_service.setBorder(null);
        tanggal_service.setEnabled(false);
        tanggal_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_serviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jenis_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(61, 61, 61)
                        .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addComponent(harga_service)
                        .addComponent(jLabel12)
                        .addComponent(harga_sparepart)
                        .addComponent(jLabel13)
                        .addComponent(total_service, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_updateService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(269, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga_sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_updateService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jenis_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 113, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void harga_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_serviceActionPerformed

    private void harga_sparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_sparepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_sparepartActionPerformed

    private void total_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_serviceActionPerformed

    private void id_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_customerActionPerformed

    private void btn_updateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateServiceActionPerformed
        // TODO add your handling code here:
        if (validateDataService()) {
            ServiceManager.updateService(serviceGlobal, Integer.parseInt(no_service.getText()));
            a.resetService();
            a.initTableService("");
            this.dispose();
        }
    }//GEN-LAST:event_btn_updateServiceActionPerformed

    private void tanggal_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_serviceActionPerformed

    private void harga_serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_serviceKeyReleased
        // TODO add your handling code here:
        if (harga_service.getText().isEmpty()) {
            harga_service.setText("0");
        }

        if (harga_sparepart.getText().isEmpty()) {
            harga_sparepart.setText("0");
        }

        int hargaService = Integer.parseInt(harga_service.getText());
        int hargaSparepart = Integer.parseInt(harga_sparepart.getText());

        total_service.setText(String.valueOf(hargaService + hargaSparepart));
    }//GEN-LAST:event_harga_serviceKeyReleased

    private void harga_sparepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_sparepartKeyReleased
        // TODO add your handling code here:
        if (harga_service.getText().isEmpty()) {
            harga_service.setText("0");
        }

        if (harga_sparepart.getText().isEmpty()) {
            harga_sparepart.setText("0");
        }

        int hargaService = Integer.parseInt(harga_service.getText());
        int hargaSparepart = Integer.parseInt(harga_sparepart.getText());

        total_service.setText(String.valueOf(hargaService + hargaSparepart));
    }//GEN-LAST:event_harga_sparepartKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_editservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_updateService;
    private javax.swing.JTextField harga_service;
    private javax.swing.JTextField harga_sparepart;
    private javax.swing.JTextField id_customer;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis_barang;
    private javax.swing.JTextField kerusakan;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField no_service;
    private javax.swing.JTextField tanggal_service;
    private javax.swing.JTextField total_service;
    // End of variables declaration//GEN-END:variables
}
