/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service.ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import service.helper.ConnectionHelper;
import service.model.Customer;
import service.model.CustomerManager;
import service.model.Service;
import service.model.ServiceManager;
import service.model.UserManager;

/**
 *
 * @author CodeVector
 */
public class form_tambahservice extends javax.swing.JFrame {

    Service serviceGlobal;
    public static int id_user = 1;

    public form_menu a = null;

    /**
     * Creates new form form_login
     */
    public form_tambahservice() {
        initComponents();        
no_service.setText(String.valueOf(ServiceManager.getLastIdService()));

    }

    public form_tambahservice(int id_customer) {
        initComponents();
//        System.out.println();
        try {
            no_service.setText(String.valueOf(ServiceManager.getLastIdService()));
            setCustomerToComponent(id_customer);
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }

    }

    public void setCustomerToComponent(int id_customer) {
        try {
            Customer customer = CustomerManager.showCustomer(id_customer);
            System.out.println("asdf"+customer.toString());
            customer.setId_customer(id_customer);
            this.id_customer.setText(String.valueOf(id_customer));
            nama_customer.setText(customer.getNama());
            alamat_customer.setText(customer.getAlamat());
            telp_customer.setText(customer.getNo_hp());
        } catch (Exception e) {
            System.out.println("error" + e.getMessage());
        }
    }

    public Boolean validateDataService() {
        boolean isCompleted = false;
        Service service = new Service();
      
        service.setId_user(id_user);

        if (id_customer.getText().isEmpty()) {
            isCompleted = false;
            btn_cariPelanggan.requestFocus(true);
        } else {
            isCompleted = true;
            service.setId_customer(Integer.parseInt(id_customer.getText()));
        }

        if (nama_barang.getText().isEmpty()) {
            isCompleted = false;
            nama_barang.requestFocus(true);
        } else {
            isCompleted = true;
            service.setNama_barang(nama_barang.getText());
        }

        if (kerusakan.getText().isEmpty()) {
            isCompleted = false;
            kerusakan.requestFocus(true);
        } else {
            isCompleted = true;
            service.setKerusakan(kerusakan.getText());
        }

        service.setJenis_barang(jenis_barang.getSelectedItem().toString());

        if (tanggal_selesai.getText().isEmpty()) {
            isCompleted = false;
            tanggal_selesai.requestFocus(true);
        } else {
            isCompleted = true;
            service.setTgl_selesai(tanggal_selesai.getText());
        }

        service.setTgl_service(tanggal_service.getText());

        if (sparepart.getText().isEmpty()) {
            service.setSparepart("");
        } else {
            isCompleted = true;
            service.setSparepart(sparepart.getText());
        }

        if (harga_sparepart.getText().isEmpty()) {
            service.setHarga_sparepart(0);
        } else {
            service.setHarga_sparepart(Integer.parseInt(harga_sparepart.getText()));
        }

        if (harga_service.getText().isEmpty()) {
            isCompleted = false;
            harga_service.requestFocus(true);
        } else {
            isCompleted = true;
            service.setHarga_service(Integer.parseInt(harga_service.getText()));
        }
        if (total_service.getText().isEmpty()) {
            isCompleted = false;
            total_service.requestFocus(true);
        } else {
            isCompleted = true;
            service.setTotal_harga(Integer.parseInt(total_service.getText()));
        }

        serviceGlobal = service;
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_cariPelanggan = new javax.swing.JButton();
        no_service = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JTextField();
        sparepart = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kerusakan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tambah_tanggal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nama_customer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        alamat_customer = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telp_customer = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        harga_service = new javax.swing.JTextField();
        btn_tambahService = new javax.swing.JButton();
        harga_sparepart = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_service = new javax.swing.JTextField();
        id_customer = new javax.swing.JTextField();
        tanggal_selesai = new javax.swing.JTextField();
        jenis_barang = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tanggal_service = new javax.swing.JTextField();
        check_cetak = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 52, 71));
        jLabel4.setText("Tambah Service");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btn_cariPelanggan.setBackground(new java.awt.Color(102, 102, 102));
        btn_cariPelanggan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cariPelanggan.setForeground(new java.awt.Color(39, 52, 71));
        btn_cariPelanggan.setText("...");
        btn_cariPelanggan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_cariPelanggan.setContentAreaFilled(false);
        btn_cariPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariPelangganActionPerformed(evt);
            }
        });

        no_service.setEditable(false);
        no_service.setBackground(new java.awt.Color(248, 248, 248));
        no_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        no_service.setForeground(new java.awt.Color(137, 144, 155));
        no_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 52, 71));
        jLabel2.setText("No Service");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 52, 71));
        jLabel3.setText("Nama Barang");

        nama_barang.setBackground(new java.awt.Color(248, 248, 248));
        nama_barang.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        nama_barang.setForeground(new java.awt.Color(137, 144, 155));
        nama_barang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        sparepart.setBackground(new java.awt.Color(248, 248, 248));
        sparepart.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        sparepart.setForeground(new java.awt.Color(137, 144, 155));
        sparepart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 52, 71));
        jLabel5.setText("Sparepart");

        kerusakan.setBackground(new java.awt.Color(248, 248, 248));
        kerusakan.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        kerusakan.setForeground(new java.awt.Color(137, 144, 155));
        kerusakan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 52, 71));
        jLabel6.setText("Kerusakan");

        tambah_tanggal.setBackground(new java.awt.Color(248, 248, 248));
        tambah_tanggal.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tambah_tanggal.setForeground(new java.awt.Color(137, 144, 155));
        tambah_tanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        tambah_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_tanggalActionPerformed(evt);
            }
        });
        tambah_tanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tambah_tanggalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tambah_tanggalKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 52, 71));
        jLabel7.setText("Tanggal Selesai");

        nama_customer.setEditable(false);
        nama_customer.setBackground(new java.awt.Color(248, 248, 248));
        nama_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        nama_customer.setForeground(new java.awt.Color(137, 144, 155));
        nama_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        nama_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_customerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 52, 71));
        jLabel8.setText("Nama Pelanggan");

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(39, 52, 71));
        jLabel9.setText("Alamat Pelanggan");

        alamat_customer.setEditable(false);
        alamat_customer.setBackground(new java.awt.Color(248, 248, 248));
        alamat_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        alamat_customer.setForeground(new java.awt.Color(137, 144, 155));
        alamat_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        alamat_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamat_customerActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(39, 52, 71));
        jLabel10.setText("No HP");

        telp_customer.setEditable(false);
        telp_customer.setBackground(new java.awt.Color(248, 248, 248));
        telp_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        telp_customer.setForeground(new java.awt.Color(137, 144, 155));
        telp_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        telp_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telp_customerActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(39, 52, 71));
        jLabel11.setText("Harga Service");

        harga_service.setBackground(new java.awt.Color(248, 248, 248));
        harga_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        harga_service.setForeground(new java.awt.Color(137, 144, 155));
        harga_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        harga_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_serviceActionPerformed(evt);
            }
        });
        harga_service.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_serviceKeyReleased(evt);
            }
        });

        btn_tambahService.setBackground(new java.awt.Color(39, 52, 71));
        btn_tambahService.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_tambahService.setForeground(new java.awt.Color(248, 248, 248));
        btn_tambahService.setText("Tambah Service");
        btn_tambahService.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        btn_tambahService.setContentAreaFilled(false);
        btn_tambahService.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tambahService.setOpaque(true);
        btn_tambahService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahServiceActionPerformed(evt);
            }
        });

        harga_sparepart.setBackground(new java.awt.Color(248, 248, 248));
        harga_sparepart.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        harga_sparepart.setForeground(new java.awt.Color(137, 144, 155));
        harga_sparepart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        harga_sparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_sparepartActionPerformed(evt);
            }
        });
        harga_sparepart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                harga_sparepartKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(39, 52, 71));
        jLabel12.setText("Harga Sparepart");

        jLabel13.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(39, 52, 71));
        jLabel13.setText("Total Harga Service");

        total_service.setBackground(new java.awt.Color(248, 248, 248));
        total_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        total_service.setForeground(new java.awt.Color(137, 144, 155));
        total_service.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        total_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_serviceActionPerformed(evt);
            }
        });

        id_customer.setBackground(new java.awt.Color(51, 51, 51));
        id_customer.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        id_customer.setBorder(null);
        id_customer.setEnabled(false);
        id_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_customerActionPerformed(evt);
            }
        });

        tanggal_selesai.setBackground(new java.awt.Color(248, 248, 248));
        tanggal_selesai.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tanggal_selesai.setForeground(new java.awt.Color(137, 144, 155));
        tanggal_selesai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        tanggal_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_selesaiActionPerformed(evt);
            }
        });

        jenis_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Komputer", "Laptop", "Printer" }));

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(39, 52, 71));
        jLabel14.setText("Jenis Barang");

        tanggal_service.setBackground(new java.awt.Color(51, 51, 51));
        tanggal_service.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        tanggal_service.setBorder(null);
        tanggal_service.setEnabled(false);
        tanggal_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal_serviceActionPerformed(evt);
            }
        });

        check_cetak.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        check_cetak.setText("Cetak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jenis_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(telp_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(alamat_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_cariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11)
                                        .addComponent(harga_service, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambah_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggal_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12)
                        .addComponent(harga_sparepart)
                        .addComponent(jLabel13)
                        .addComponent(total_service, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(check_cetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_tambahService, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(311, 311, 311)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggal_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_cariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga_sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kerusakan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jenis_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telp_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_tambahService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(check_cetak))
                            .addComponent(harga_service, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(tanggal_service, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tambah_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambah_tanggalActionPerformed

    private void nama_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_customerActionPerformed

    private void alamat_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamat_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamat_customerActionPerformed

    private void telp_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telp_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telp_customerActionPerformed

    private void harga_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_serviceActionPerformed

    private void btn_cariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariPelangganActionPerformed
        // TODO add your handling code here:
        form_pilihpelanggan a = new form_pilihpelanggan();
        a.tambahService = this;
        a.setVisible(true);
    }//GEN-LAST:event_btn_cariPelangganActionPerformed

    private void harga_sparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_sparepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_sparepartActionPerformed

    private void total_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_serviceActionPerformed

    private void id_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_customerActionPerformed

    private void tanggal_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_selesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_selesaiActionPerformed

    private void tambah_tanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambah_tanggalKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tambah_tanggalKeyPressed

    private void tambah_tanggalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tambah_tanggalKeyReleased
        try {
            String tgl = tambah_tanggal.getText();
            if (tgl == "") {
                tambah_tanggal.setText("0");
            }
            Date date = new Date();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Calendar c = Calendar.getInstance();
            c.setTime(date);
            tanggal_service.setText(sdf.format(c.getTime()));
            c.add(Calendar.DATE, Integer.parseInt(tgl));
            tanggal_selesai.setText(sdf.format(c.getTime()));

        } catch (Exception e) {

        }
    }//GEN-LAST:event_tambah_tanggalKeyReleased

    private void btn_tambahServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahServiceActionPerformed
        // TODO add your handling code here:
        if (validateDataService()) {
            if (check_cetak.isSelected()) {
                ServiceManager.insertService(serviceGlobal);
                a.initTableService("");                
                try {
                    HashMap parameter = new HashMap();

                    parameter.put("no_service", ServiceManager.getLastIdService());
                    parameter.put("tanggal_service", tanggal_service.getText());
                    parameter.put("nama_pelanggan", nama_customer.getText());
                    parameter.put("telpon", telp_customer.getText());
                    parameter.put("nama_barang", nama_barang.getText());
                    parameter.put("jenis_barang", jenis_barang.getSelectedItem().toString());
                    parameter.put("kerusakan", kerusakan.getText());
                    System.out.println(parameter.toString());
                    JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream(""
                            + "/service/report/ReportService.jasper"), 
                            parameter, ConnectionHelper.getConnection());

                    JasperViewer.viewReport(jp, false);
                } catch (Exception e) {
                    Logger.getLogger(form_tambahservice.class.getName()).log(Level.SEVERE, null, e);

                }
                this.dispose();

            } else {
                ServiceManager.insertService(serviceGlobal);
                a.initTableService("");
                a.resetService();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btn_tambahServiceActionPerformed

    private void tanggal_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal_serviceActionPerformed

    private void harga_serviceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_serviceKeyReleased
        // TODO add your handling code here:
        if (harga_service.getText().isEmpty()) {
            harga_service.setText("0");
        }

        if (harga_sparepart.getText().isEmpty()) {
            harga_sparepart.setText("0");
        }

        int hargaService = Integer.parseInt(harga_service.getText());
        int hargaSparepart = Integer.parseInt(harga_sparepart.getText());

        total_service.setText(String.valueOf(hargaService + hargaSparepart));
    }//GEN-LAST:event_harga_serviceKeyReleased

    private void harga_sparepartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_harga_sparepartKeyReleased
        // TODO add your handling code here:
        if (harga_service.getText().isEmpty()) {
            harga_service.setText("0");
        }

        if (harga_sparepart.getText().isEmpty()) {
            harga_sparepart.setText("0");
        }

        int hargaService = Integer.parseInt(harga_service.getText());
        int hargaSparepart = Integer.parseInt(harga_sparepart.getText());

        total_service.setText(String.valueOf(hargaService + hargaSparepart));
    }//GEN-LAST:event_harga_sparepartKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_dataservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_tambahservice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_customer;
    private javax.swing.JButton btn_cariPelanggan;
    private javax.swing.JButton btn_tambahService;
    private javax.swing.JCheckBox check_cetak;
    private javax.swing.JTextField harga_service;
    private javax.swing.JTextField harga_sparepart;
    private javax.swing.JTextField id_customer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis_barang;
    private javax.swing.JTextField kerusakan;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField nama_customer;
    private javax.swing.JTextField no_service;
    private javax.swing.JTextField sparepart;
    private javax.swing.JTextField tambah_tanggal;
    private javax.swing.JTextField tanggal_selesai;
    private javax.swing.JTextField tanggal_service;
    private javax.swing.JTextField telp_customer;
    private javax.swing.JTextField total_service;
    // End of variables declaration//GEN-END:variables
}
