 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package service.ui;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.model.Customer;
import service.model.CustomerManager;
import service.ui.form_tambahservice;

/**
 *
 * @author CodeVector
 */
public class form_pilihpelanggan extends javax.swing.JFrame {

    public static DefaultTableModel tableModel;
    public static List<Customer> listCustomer;    
    Customer customerGlobal;
    
    public form_tambahservice tambahService = null;

    /**
     * Creates new form form_login
     */
    public form_pilihpelanggan() {
        initComponents();
        initTable("");
    }

    public void initTable(String q) {
        tb_customer.setRowHeight(30);
        id_customer.setText(String.valueOf(CustomerManager.getLastIdCustomer()));

        tableModel = (DefaultTableModel) tb_customer.getModel();
        tableModel.setRowCount(0);
        listCustomer = new ArrayList<>();
        listCustomer = CustomerManager.showAllCustomer(q);
        System.out.println(listCustomer);
        listCustomer.forEach(customer -> {
            tableModel.addRow(new Object[]{
                customer.getId_customer(),
                customer.getNama(),
                customer.getAlamat(),
                customer.getNo_hp(),});
        });
    }

    private boolean validateData() {
        boolean isCompleted = false;
        Customer customer = new Customer();

        if (nama_customer.getText().isEmpty()) {
            isCompleted = false;
            nama_customer.requestFocus(true);
        } else {
            isCompleted = true;
            customer.setNama(nama_customer.getText());
        }

        if (alamat_customer.getText().isEmpty()) {
            isCompleted = false;
            alamat_customer.requestFocus(true);
        } else {
            isCompleted = true;
            customer.setAlamat(alamat_customer.getText());
        }

        if (no_hp.getText().isEmpty()) {
            isCompleted = false;
            no_hp.requestFocus(true);
        } else {
            isCompleted = true;
            customer.setNo_hp(no_hp.getText());
        }

        customerGlobal = customer;
        return true;

    }

    public void resetField() {
        
        nama_customer.setText("");
        alamat_customer.setText("");
        no_hp.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        id_customer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_customer = new javax.swing.JTextField();
        no_hp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        alamat_customer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_tambahCustomer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_customer = new javax.swing.JTable();
        btn_pilihCustomer = new javax.swing.JButton();
        pencarian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 52, 71));
        jLabel4.setText("Data Pelanggan");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        id_customer.setEditable(false);
        id_customer.setBackground(new java.awt.Color(248, 248, 248));
        id_customer.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        id_customer.setForeground(new java.awt.Color(204, 204, 204));
        id_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 52, 71));
        jLabel2.setText("No Pelanggan");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 52, 71));
        jLabel3.setText("Nama Pelanggan");

        nama_customer.setBackground(new java.awt.Color(248, 248, 248));
        nama_customer.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        nama_customer.setForeground(new java.awt.Color(204, 204, 204));
        nama_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        no_hp.setBackground(new java.awt.Color(248, 248, 248));
        no_hp.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        no_hp.setForeground(new java.awt.Color(204, 204, 204));
        no_hp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(39, 52, 71));
        jLabel5.setText("No HP");

        alamat_customer.setBackground(new java.awt.Color(248, 248, 248));
        alamat_customer.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        alamat_customer.setForeground(new java.awt.Color(204, 204, 204));
        alamat_customer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 52, 71));
        jLabel6.setText("Alamat Pelanggan");

        btn_tambahCustomer.setBackground(new java.awt.Color(39, 52, 71));
        btn_tambahCustomer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_tambahCustomer.setForeground(new java.awt.Color(248, 248, 248));
        btn_tambahCustomer.setText("Tambah");
        btn_tambahCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btn_tambahCustomer.setContentAreaFilled(false);
        btn_tambahCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tambahCustomer.setOpaque(true);
        btn_tambahCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahCustomerActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);

        tb_customer.setBackground(new java.awt.Color(248, 248, 248));
        tb_customer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tb_customer.setForeground(new java.awt.Color(137, 144, 155));
        tb_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama Pelanggan", "Alamat Pelanggan", "No HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_customer.setGridColor(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tb_customer);

        btn_pilihCustomer.setBackground(new java.awt.Color(39, 52, 71));
        btn_pilihCustomer.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_pilihCustomer.setForeground(new java.awt.Color(248, 248, 248));
        btn_pilihCustomer.setText("Pilih Pelanggan");
        btn_pilihCustomer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btn_pilihCustomer.setContentAreaFilled(false);
        btn_pilihCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pilihCustomer.setOpaque(true);
        btn_pilihCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihCustomerActionPerformed(evt);
            }
        });

        pencarian.setBackground(new java.awt.Color(248, 248, 248));
        pencarian.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        pencarian.setForeground(new java.awt.Color(204, 204, 204));
        pencarian.setText("Cari");
        pencarian.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 102)));
        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });
        pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pencarianKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(no_hp, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(id_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(alamat_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(nama_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btn_tambahCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pilihCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nama_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alamat_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tambahCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pilihCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahCustomerActionPerformed
        // TODO add your handling code here:
        try {
            if (validateData()) {
                CustomerManager.insertCustomer(customerGlobal);
                initTable("");
                resetField();
            }
        } catch (Exception e) {
            Logger.getLogger(form_pilihpelanggan.class.getName()).log(Level.SEVERE, null, e);

        }
    }//GEN-LAST:event_btn_tambahCustomerActionPerformed

    private void btn_pilihCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihCustomerActionPerformed
        // TODO add your handling code here:
        imdone();
        
    }//GEN-LAST:event_btn_pilihCustomerActionPerformed

    private void pencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pencarianKeyReleased
        // TODO add your handling code here:
        initTable(pencarian.getText());
    }//GEN-LAST:event_pencarianKeyReleased

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianActionPerformed
 
    void imdone(){
        try {
            int selectedRow = tb_customer.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "", "Pilih baris dulu", 2);
            } else {
                String nama=tb_customer.getValueAt(selectedRow, 1).toString(); 
                Customer customer = listCustomer.get(selectedRow);
                tambahService.setCustomerToComponent(customer.getId_customer());                
                this.dispose();
            }
        } catch (Exception e) {
            Logger.getLogger(form_pilihpelanggan.class.getName()).log(Level.SEVERE, null, e);


        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pilihpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pilihpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pilihpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pilihpelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pilihpelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat_customer;
    private javax.swing.JButton btn_pilihCustomer;
    private javax.swing.JButton btn_tambahCustomer;
    private javax.swing.JTextField id_customer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama_customer;
    private javax.swing.JTextField no_hp;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTable tb_customer;
    // End of variables declaration//GEN-END:variables
}
